name: eshop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  badges: null
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/